### ISSUE TITLE
new version pushed to github

### ISSUE THREAD

**Issue by aleksandersumowski** [twitter-archive/scala-zookeeper-client#10]
Are you planning to continue updating the github repo? I can see that Twitter maven repository has a newer version than github.

**Comment by ryanking** [comment]
I wll push the latests to github, but answer your question– no, we will not be updating this project anymore.

**Comment by aleksandersumowski** [comment]
Have you started using another client?

**Comment by aleksandersumowski** [comment]
ok, I've found the util project. one final question: could you update the project description to point to util project so that other people are sparred the search? Thanks!

**Comment by ryanking** [comment]
Yeah, sorry. I thought I'd already documented this.
