### ISSUE TITLE
Request for Exists method

### ISSUE THREAD

**Issue by datacoda** [twitter-archive/scala-zookeeper-client#4]
Thanks for the ZooKeeper wrapper.  Sanity +1.  However, unless there's a better way to check for whether a znode exists, could we merge the exist function from the foursquare fork?

Their commit is provided below:

https://github.com/foursquare/scala-zookeeper-client/commit/e0371e9b52fb9b4973096e7f58c54006f7f80f00

**Comment by ryanking** [comment]
We can totally merge that.

**Comment by datacoda** [comment]
Closing due to deprecation.
